### ISSUE TITLE
Webpage is down for tutorial.

### ISSUE THREAD

**Issue by WilliamBaltus** [open-navigation/navigation2#4303]
404 error for any nav2 page try to open up. Also how can I join the slack? It says I need domain or contact nav2 administrators.

**Comment by SteveMacenski** [comment]
See https://docs.nav2.org/, it was announced in https://discourse.ros.org/t/new-nav2-website/37582

**Comment by SteveMacenski** [comment]
Slack link: https://join.slack.com/t/navigation2/shared_invite/zt-uj428p0x-jKx8U7OzK1IOWp5TnDS2rA

**Comment by WilliamBaltus** [comment]
Ty
