### ISSUE TITLE
all Github Pages documentations return 404

### ISSUE THREAD

**Issue by aatb-ch** [open-navigation/navigation2#4306]
As of yesterday night, all documentations at [navigation.ros.org](https://navigation.ros.org/) return 404. GH says all services are green so maybe there was some config mishap?

<img width="1096" alt="Screenshot 2024-05-07 at 11 42 50" src="https://github.com/open-navigation/navigation2/assets/60657807/d452fd3d-3e99-4da9-9155-e8c2e5ea6558">

**Comment by aatb-ch** [comment]
All available on Wayback Machine in the meantime [here](https://web.archive.org/web/20240420053823/https://navigation.ros.org/index.html)

**Comment by tonynajjar** [comment]
Please refer to https://github.com/open-navigation/navigation2/issues/4303

**Comment by aatb-ch** [comment]
oh, missed that, thanks!
