### ISSUE TITLE
MPPI dynamic parameter not working with vx_max

### ISSUE THREAD

**Issue by Huyhust13** [open-navigation/navigation2#4315]
## Bug report

**Required Info:**

- Operating System: Ubuntu 22.04
- ROS2 Version: Humble
- Version or commit hash: 150dd6beb50aee502ada8935cee23d7160a40f57
- DDS implementation: mw_cyclonedds_cpp

#### Expected behavior

I set vx_max = 0.5 in file parameter, then when it is running, I change the vx_max to 0.3. I use `parameter get` to show param, it shows vx_max = 0.3 but the robot runs with vx = 0.5.

**Comment by Huyhust13** [comment]
Thank for your replying @SteveMacenski. 
I'll do test.

**Comment by Huyhust13** [comment]
It's correct, it works now @SteveMacenski 
Thank you very much for your help.

**Comment by YoungRicky7** [comment]
> ## Bug report
> **Required Info:**
> 
> * Operating System: Ubuntu 22.04
> * ROS2 Version: Humble
> * Version or commit hash: [150dd6b](https://github.com/ros-navigation/navigation2/commit/150dd6beb50aee502ada8935cee23d7160a40f57)
> * DDS implementation: mw_cyclonedds_cpp
> 
> #### Expected behavior
> I set vx_max = 0.5 in file parameter, then when it is running, I change the vx_max to 0.3. I use `parameter get` to show param, it shows vx_max = 0.3 but the robot runs with vx = 0.5.

How do I change the speed while robot is running? it seems no matter what parameters that I change the speed of robot stays around 0.26m/s
