### ISSUE TITLE
Can MPPI follow the global path that represents reversing movement of the robot?

### ISSUE THREAD

**Issue by bojan-otsaw** [open-navigation/navigation2#4318]
Hi ,

I have a global path planner that outputs a global path, and depending of the scenario in same cases the robot should move forward and follow the forward path. But in  same scenario  when a forward global path is giver  and on the way moving forward the robot find an obstacle in narrow corridor that is not possible to avoid, in that case it should move reverse back  and than find alternative path forward to  to move to the goal position

Given this context, my question is, can the current implementation of MPPI controller follow a global path like this? If not, what will be the best way to modify it to achieve this?

Thank you very much.

**Comment by SteveMacenski** [comment]
Yes! See @doisyg’s ROSCon talk on this matter: https://vimeo.com/879000809/b32f8ebec4

**Comment by bojan-otsaw** [comment]
But my robot is AMR not and AGV . Can not turn on the spot. So is still possible?

**Comment by SteveMacenski** [comment]
Please see the video
